###
# Testing (update BASE_URL if environment differs)
@baseUrl = http://localhost:5001

GET {{baseUrl}}/api/shared/me

###
POST {{baseUrl}}/api/shared/login
Content-Type: application/json

{
    "email": "dandigeming85@gmail.com",
    "password": "123"
}